pipeline {
    agent any
    triggers { githubPush() } // ensures push events trigger build

    stages {
        stage('Build on Push') {
            when {
                branch 'main'  // only run when pushing to main
            }
            steps {
                echo "Building because of a push to main"
            }
        }

        stage('Build on PR') {
            when {
                changeRequest() // only runs for PR builds
            }
            steps {
                echo "Building because of a Pull Request"
            }
        }
    }
}
